# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fenetrePrincipale.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FenetrePrincipale(object):
    def setupUi(self, FenetrePrincipale):
        FenetrePrincipale.setObjectName("FenetrePrincipale")
        FenetrePrincipale.resize(635, 501)
        self.gridLayout = QtWidgets.QGridLayout(FenetrePrincipale)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_creerNote = QtWidgets.QPushButton(FenetrePrincipale)
        self.btn_creerNote.setObjectName("btn_creerNote")
        self.gridLayout.addWidget(self.btn_creerNote, 0, 0, 1, 1)
        self.btn_supprimerNote = QtWidgets.QPushButton(FenetrePrincipale)
        self.btn_supprimerNote.setObjectName("btn_supprimerNote")
        self.gridLayout.addWidget(self.btn_supprimerNote, 0, 1, 1, 1)
        self.lw_listeDeNotes = QtWidgets.QListWidget(FenetrePrincipale)
        self.lw_listeDeNotes.setObjectName("lw_listeDeNotes")
        self.gridLayout.addWidget(self.lw_listeDeNotes, 1, 0, 2, 2)
        self.te_contenuDeLaNote = QtWidgets.QTextEdit(FenetrePrincipale)
        self.te_contenuDeLaNote.setObjectName("te_contenuDeLaNote")
        self.gridLayout.addWidget(self.te_contenuDeLaNote, 1, 2, 1, 1)
        self.btn_mettreAjourNote = QtWidgets.QPushButton(FenetrePrincipale)
        self.btn_mettreAjourNote.setObjectName("btn_mettreAjourNote")
        self.gridLayout.addWidget(self.btn_mettreAjourNote, 2, 2, 1, 1)

        self.retranslateUi(FenetrePrincipale)
        QtCore.QMetaObject.connectSlotsByName(FenetrePrincipale)

    def retranslateUi(self, FenetrePrincipale):
        _translate = QtCore.QCoreApplication.translate
        FenetrePrincipale.setWindowTitle(_translate("FenetrePrincipale", "Createur de notes"))
        self.btn_creerNote.setText(_translate("FenetrePrincipale", "Creer une note"))
        self.btn_supprimerNote.setText(_translate("FenetrePrincipale", "Supprimer la note"))
        self.btn_mettreAjourNote.setText(_translate("FenetrePrincipale", "Mettre a jour"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FenetrePrincipale = QtWidgets.QWidget()
    ui = Ui_FenetrePrincipale()
    ui.setupUi(FenetrePrincipale)
    FenetrePrincipale.show()
    sys.exit(app.exec_())
