ignore: []

refactor:
  skip: []

metrics:
  enabled: false
  quality_threshold: 5.0

github:
  labels: []
  ignore_labels: [sourcery-ignore]
  request_review: author
  sourcery_branch: sourcery/{base_branch}